"""
Constants and configuration for Chess Game
"""

# Server Configuration
SERVER_HOST = '0.0.0.0'  # Listen on all network interfaces (LAN + localhost)
SERVER_PORT = 5555
BUFFER_SIZE = 4096
MAX_CONNECTIONS = 10

# Game Configuration
BOARD_SIZE = 8
DEFAULT_TIME_CONTROL = 600  # 10 minutes per player

# Message Types
MSG_LOGIN = "LOGIN"
MSG_LOGOUT = "LOGOUT"
MSG_CREATE_ROOM = "CREATE_ROOM"
MSG_JOIN_ROOM = "JOIN_ROOM"
MSG_LEAVE_ROOM = "LEAVE_ROOM"
MSG_LIST_ROOMS = "LIST_ROOMS"
MSG_MOVE = "MOVE"
MSG_RESIGN = "RESIGN"
MSG_OFFER_DRAW = "OFFER_DRAW"
MSG_ACCEPT_DRAW = "ACCEPT_DRAW"
MSG_DECLINE_DRAW = "DECLINE_DRAW"
MSG_CHAT = "CHAT"
MSG_UNDO = "UNDO"
MSG_REDO = "REDO"

# Response Types
MSG_LOGIN_SUCCESS = "LOGIN_SUCCESS"
MSG_LOGIN_FAILED = "LOGIN_FAILED"
MSG_ROOM_LIST = "ROOM_LIST"
MSG_ROOM_JOINED = "ROOM_JOINED"
MSG_GAME_START = "GAME_START"
MSG_MOVE_UPDATE = "MOVE_UPDATE"
MSG_GAME_OVER = "GAME_OVER"
MSG_TURN_UPDATE = "TURN_UPDATE"
MSG_CHAT_MESSAGE = "CHAT_MESSAGE"
MSG_ERROR = "ERROR"

# Game Status
STATUS_WAITING = "waiting"
STATUS_PLAYING = "playing"
STATUS_FINISHED = "finished"

# Colors
COLOR_WHITE = "white"
COLOR_BLACK = "black"

# Game Results
RESULT_WHITE_WIN = "white_win"
RESULT_BLACK_WIN = "black_win"
RESULT_DRAW = "draw"

# End Reasons
END_CHECKMATE = "checkmate"
END_RESIGN = "resign"
END_TIMEOUT = "timeout"
END_STALEMATE = "stalemate"
END_DRAW = "draw_agreement"
